sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t pavanjdot/docker-colorpicker-reactapp -f Dockerfile.dev . 

script: 
  - docker run -e CI=true pavanjdot/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-colorpicker-reactapp"
  env: "Dockercolorpickerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-077976234237"
  bucket_path: "docker-colorpicker-reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY